{
    'name': 'Stripe Connector',
    'version': '19.0.1.0.0',
    'category': 'Accounting/Accounting',
    'summary': 'Fetch Stripe invoices and credit notes into Odoo accounting',
    'author': 'Custom',
    'depends': ['account', 'mail'],
    'data': [
        'security/security.xml',
        'data/ir_cron.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/stripe_account_views.xml',
        'views/stripe_import_run_views.xml',
        'views/account_journal_dashboard_views.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
